# Configuration file for BW-Parkour
# The block-world option turns on features hardcoded to the Block World server, this should not be turned on
# block-cmds will stop commands being ran in a parkour arena, commands in allowed-cmds will be ignored
# spawn-world-name should be set to the world you want players to spawn in after exiting the arena
# The coordinates and the checkpoints options take coordinates in the format of x,y,z
# The world-name option in each arena should be set to the world that that arena is in
# Players will get the amount of money specified in the reward option upon finishing the arena, this utilizes Vault
# If you need help don't hesitate to comment on the project page asking for it
# And seriously, don't change dont-ever-change-this as it will wipe your configuration
dont-ever-change-this: 1
block-world: false
block-cmds: true
spawn-world-name: world
arenas:
    arenaexample1:
        coordinates: 100,80,300
        world-name: world
        reward: 500
        checkpoints:
            1: 105,80,300
            2: 110,80,300
            3: 115,80,300
            4: 120,80,300
            5: 125,80,300
            6: 130,80,300
    arenaexample2:
        coordinates: 500,80,900
        world-name: world
        reward: 1000
        checkpoints:
            first: 505,80,900
            second: 510,80,900
            third: 515,80,900
            fourth: 520,80,900
    arenaexample3:
        coordinates: 1600,80,400
        world-name: world
        reward: 1500
        checkpoints:
            island: 1605,80,400
            cloud: 1610,80,400
            tree: 1615,80,400
            fence: 1620,80,400
            road: 1625,80,400
allowed-cmds:
    - bwp