# Configuration file for BW-Parkour
# If you need help don't hesitate to comment on the project page asking for it
# And seriously, don't change dont-ever-change-this as it will wipe your configuration
dont-ever-change-this: 1