# Configuration file for BW-Parkour
# The region-name option refers to a WorldGuard region that should be created for the parkour arena
# The coordinates option refers to where players will be teleported to when entering the arena
# If you need help don't hesitate to comment on the project page asking for it
# And seriously, don't change dont-ever-change-this as it will wipe your configuration
dont-ever-change-this: 1
world-name: world
arenas:
    arenaexample1:
        region-name: thearena1
        coordinates: 100,80,300
        reward: 500
    arenaexample2:
        region-name: thearena2
        coordinates: 500,80,900
        reward: 1000
    arenaexample3:
        region-name: thearena3
        coordinates: 1600,80,400
        reward: 1500