name: BW-Parkour
main: com.vauff.bwparkour.core.Main
version: 0.1
author: Vauff
depend: [Vault]
commands:
    bwp:
        description: The main command for BW-Parkour
        usage: /bwp <option>
permissions:
    bwparkour.about:
        description: Gives permission to the about command, shows you plugin information
        default: true
    bwparkour.help:
        description: Gives permission to the help command, gives you help with different command options
        default: true
    bwparkour.reload:
        description: Gives permission to the reload command, reloads the configuration file
        default: op
    bwparkour.place:
        description: Gives permission to place BW-Parkour signs, used for arena interactions
        default: op
    bwparkour.exit:
        description: Gives permission to the exit command and sign, allows you to leave a parkour arena
        default: true
    bwparkour.enter:
        description: Gives permission to the enter command and sign, allows you to enter a parkour arena
        default: true
    bwparkour.tp:
        description: Gives permission to the tp command and sign, lets you tp to your last checkpoint
        default: true
    bwparkour.checkpoint:
        description: Gives permission to the checkpoint sign, lets you set a new checkpoint
        default: true
    bwparkour.finish:
        description: Gives permission to the finish sign, lets you finish a parkour arena
        default: true