name: IC-Parkour
main: com.vauff.icparkour.core.Main
version: 1.2-dev
author: Vauff
depend: [Vault]
commands:
    icp:
        description: The main command for IC-Parkour
        usage: /icp <option>
permissions:
    icparkour.about:
        description: Gives permission to the about command, shows you plugin information
        default: true
    icparkour.help:
        description: Gives permission to the help command, gives you help with different command options
        default: true
    icparkour.reload:
        description: Gives permission to the reload command, reloads the configuration file
        default: op
    icparkour.remove:
        description: Gives permission to the icp remove command, used to remove parkour arenas
        default: op
    icparkour.place:
        description: Gives permission to place BW-Parkour signs, used for arena interactions
        default: op
    icparkour.bypasscmdblock:
        description: Gives permission to bypass the command blocking, for when in parkour arenas
        default: op
    icparkour.exit:
        description: Gives permission to the exit command and sign, allows you to leave a parkour arena
        default: true
    icparkour.enter:
        description: Gives permission to the enter command and sign, allows you to enter a parkour arena
        default: true
    icparkour.tp:
        description: Gives permission to the tp command and sign, lets you tp to your last checkpoint
        default: true
    icparkour.checkpoint:
        description: Gives permission to the checkpoint sign, lets you set a new checkpoint
        default: true
    icparkour.finish:
        description: Gives permission to the finish sign, lets you finish a parkour arena
        default: true